### ISSUE TITLE
leopard.sh and tiger.sh

### ISSUE THREAD

**Issue by cellularmitosis** [kencu/kencu-ports#1]
Hi Ken,

I hope you'll forgive this abuse of the github issue system.

I've started working on a package manager which explicitly targets just Tiger and Leopard, focused on 100% binary package availability, and on speed (it should be faster on an old mac than homebrew on a modern mac), written entirely in bash.

I wanted to thank you personally for all of the effort you have poured into keeping PowerPC support alive.  Literally every time I run into a tricky compilation issue, I google it and your name appears.

Anyway, if you'd like to give it a whirl, I'd love to hear your feedback :)
- http://leopard.sh/
- https://github.com/cellularmitosis/leopard.sh

Cheers!

**Comment by kencu** [comment]
I have a collection of these machines from past businesses, almost all still running, so I enjoyed keeping them useful. Your project looks fun, lots of interest out there still in PPC on Darwin.

I’ll take it for a test run!
